=== tomo-waka/gent/packages/gent/schema/program-options.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/tomo-waka/gent/main/packages/gent/schema/program-options.schema.json",
  "title": "GenT ProgramOptions (meta file)",
  "type": "object",
  "properties": {
    "debug": {
      "type": "boolean"
    },
    "from": {
      "type": "string",
      "format": "date-time"
    },
    "to": {
      "type": "string",
      "format": "date-time"
    },
    "count": {
      "$ref": "./common.schema.json#/$defs/numberLike"
    },
    "out": {
      "$ref": "#/$defs/outputOptions"
    },
    "templates": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/templateOptions"
      }
    }
  },
  "required": ["out", "templates"],
  "additionalProperties": false,
  "$defs": {
    "templateOptions": {
      "type": "object",
      "properties": {
        "mode": {
          "$ref": "./common.schema.json#/$defs/templateMode"
        },
        "path": {
          "type": "string",
          "minLength": 1
        },
        "weight": {
          "$ref": "./common.schema.json#/$defs/numberLike"
        }
      },
      "required": ["path"],
      "additionalProperties": false
    },
    "outputOptions": {
      "oneOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "$ref": "./output/file-output.schema.json"
        },
        {
          "$ref": "./output/udp-output.schema.json"
        },
        {
          "$ref": "./output/tcp-output.schema.json"
        },
        {
          "$ref": "./output/tls-output.schema.json"
        }
      ]
    }
  }
}

=== tomo-waka/gent/packages/gent/sample/meta.json
{
  "debug": true,
  "from": "2000-01-01T00:00:00+09:00",
  "to": "2020-12-31T23:59:59+09:00",
  "count": 100000,
  "out": {
    "type": "file",
    "path": "out/out.log",
    "size": "10M"
  },
  "templates": [
    {
      "path": "sample/syslog_RFC3164.template.log",
      "weight": 2
    },
    {
      "path": "sample/syslog_RFC3164(ISO_Date).template.log",
      "weight": 3
    },
    {
      "path": "sample/syslog_RFC5424.template.log",
      "weight": 1
    },
    {
      "path": "sample/aws_CloudWatch.json",
      "weight": 1
    }
  ]
}
